### ISSUE TITLE
line 5: have: command not found

### ISSUE THREAD

**Issue by bfontaine** [roshan/rust-bash-completion#1]
Hello,

When I source `cargo` on OS X, Bash complains that the `have` command doesn’t exist.

```
$ bash --version | head -n 1
GNU bash, version 4.3.39(1)-release (x86_64-apple-darwin14.4.0)

$ source etc/bash_completion.d/cargo
have: command not found
```

**Comment by roshan** [comment]
Did you install `bash-completion` via Homebrew? If so, did you try:

```
source `brew --prefix`/etc/bash_completion
```

**Comment by bfontaine** [comment]
Yes, and I sourced it directly without sourcing the file you mention, which indeed defines `have`. Thanks!
